const WorkProcessData = [
  {
    id: 1,
    title: "Create your web masterpiece",
    paragraph:
      "Your website is the cornerstone of your online presence. At our agency, we specialize in creating web masterpieces that stand out from the crowd. Our team of expert designers and developers will work closely with you to create a website that not only looks great but also performs at its best.Let us help you bring your vision to life and create a web masterpiece that represents your brand in the best possible light.",
    image: "/images/work/work-bg-1.png",
    user: true,
    userCount: 380,
    sale: false,
    // currentSale: 38.4,
    // previousSale: 34,
    // SaleIncrease: 4.5,
    payment: false,
    // paymentAmount: 450,
    // paymentDate: "24th May",
  },
  {
    id: 2,
    title: "Create your web masterpiece",
    paragraph:
      "Your website is the cornerstone of your online presence. At our agency, we specialize in creating web masterpieces that stand out from the crowd. Our team of expert designers and developers will work closely with you to create a website that not only looks great but also performs at its best.Let us help you bring your vision to life and create a web masterpiece that represents your brand in the best possible light.",
    image: "/images/work/work-bg-2.png",
    user: false,
    //userCount: 380,
    sale: true,
    currentSale: 38.4,
    previousSale: 34,
    SaleIncrease: 4.5,
    payment: false,
    // paymentAmount: 450,
    // paymentDate: "24th May",
  },
  {
    id: 3,
    title: "Handover the final good result.",
    paragraph:
      "Your website is the cornerstone of your online presence. At our agency, we specialize in creating web masterpieces that stand out from the crowd. Our team of expert designers and developers will work closely with you to create a website that not only looks great but also performs at its best.Let us help you bring your vision to life and create a web masterpiece that represents your brand in the best possible light.",
    image: "/images/work/work-bg-3.png",
    user: false,
    //userCount: ,
    sale: false,
    // currentSale: ,
    // previousSale:,
    // SaleIncrease:,
    payment: true,
    paymentAmount: 450,
    paymentDate: "24th May",
  },
];
export default WorkProcessData;
